### ISSUE TITLE
Install drake binary from the source

### ISSUE THREAD

**Issue by junhyeokahn** [RobotLocomotion/drake-shambhala#107]
Hello,
I am using MAC OS X, and want to use drake_cmake_installed.
In the README file, there is an instruction to install drake binaries for UBUNTU but not for MAC.
I would like to install binaries from the source, so want to use the method similar to ```sudo make install``` in ```cmake``` but I don't know the equivalent method  in ```bazel```.

Is there any way for me to install binaries from the drake source by using a method similar to ```make install``` in MAC?

Should I follow this instruction below?
```
# 3) Manual Installation
# git clone https://github.com/RobotLocomotion/drake.git
# (mkdir drake-build && cd drake-build && cmake -DCMAKE_INSTALL_PREFIX=/opt/drake ../drake && make)

# 4) Manual Installation w/ Licensed Gurobi
# Install & setup gurobi (http://drake.mit.edu/bazel.html?highlight=gurobi#install-on-ubuntu)
# git clone https://github.com/RobotLocomotion/drake.git
# (mkdir drake-build && cd drake-build && cmake -DCMAKE_INSTALL_PREFIX=/opt/drake -DWITH_GUROBI=ON ../drake && make)
```

**Comment by jwnimmer-tri** [comment]
Disclaimer: I haven't personally tried any of the below, but maybe it helps...

See also http://drake.mit.edu/from_binary.html.  In the https://github.com/RobotLocomotion/drake-shambhala/tree/master/drake_cmake_installed#instructions if you replace `-xenial` in the targz filename with `-mac` you would get the pre-compiled binary release for macOS.  If I recall correctly, the https://github.com/RobotLocomotion/drake/tree/master/setup/mac/binary_distribution prereqs script is included in the targz, but if not you can refer to that source copy instead.

I'm not sure what else has to change vs Ubuntu, but maybe that's a start.

**Comment by RussTedrake** [comment]
fwiw, the installation instructions here: http://underactuated.mit.edu/underactuated.html?chapter=drake where used successfully for the last ~6 mos (and contain mac)

**Comment by junhyeokahn** [comment]
@RussTedrake @jwnimmer-tri  Thanks, if I want to use gurobi, mosek, snopt, should I add extra snippets on installation?

**Comment by junhyeokahn** [comment]
Thank you so much!
