### ISSUE TITLE
Travis CI: Failling due to `libprotobuf.15.dylib`

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake-shambhala#111]
It seems that protobuf is causing TravisCI to fail:
One example from this build: https://travis-ci.org/RobotLocomotion/drake-shambhala/jobs/394709115#L3073-L3078
```
3: Test command: /Users/travis/build/RobotLocomotion/drake-shambhala/drake_cmake_installed/build/src/particles/particle_test
3: Test timeout computed to be: 1500
3: dyld: Library not loaded: /usr/local/opt/protobuf/lib/libprotobuf.15.dylib
3:   Referenced from: /opt/drake/lib/libdrake.so
3:   Reason: image not found
```

Should we be pinning our `protobuf` version on Homebrew?

\cc @soonho-tri Have you seen anything like this on any of your systems?

**Comment by jamiesnape** [comment]
Protobuf got updated sometime between when the nightly packages were built and when the nightly shambhala job ran. Should be resolved when the next nightly packages are built. Not much we can do about those situations.

**Comment by EricCousineau-TRI** [comment]
Confirmed that TravisCI is now passing.
