### ISSUE TITLE
Hook up Reviewable

### ISSUE THREAD

**Issue by stonier** [RobotLocomotion/drake-shambhala#15]

**Comment by jwnimmer-tri** [comment]
I volunteer to help.  Doing PRs without this (e.g., #27) is really bothering me.

If you give me admin bits, I will do it directly.  However, it might be smarter to have me shoulder surf or screenshare so others learn too.

**Comment by stonier** [comment]
I would delay this until after next week. We have more urgent requirements right now.

**Comment by jamiesnape** [comment]
Completed by @EricCousineau-TRI last week.
