### ISSUE TITLE
A 'latest' binaries sym-link

### ISSUE THREAD

**Issue by stonier** [RobotLocomotion/drake-shambhala#17]
Not sure if this is the right idea or not, but a `drake-latest.tar.gz` would automate the CI checks here so that we are not drifting away from Drake's latest releases.

**Comment by stonier** [comment]
@jamiesnape do the binaries get built nightly and automatically uploaded yet?

**Comment by jamiesnape** [comment]
Not yet.

**Comment by jamiesnape** [comment]
Unless something has changed recently, S3 does not support symlinks, so the mechanism would need to be different.

**Comment by stonier** [comment]
Understood.
