### ISSUE TITLE
Binaries do not include data files

### ISSUE THREAD

**Issue by stonier** [RobotLocomotion/drake-shambhala#18]
This is a pre-requisite of having #11 working and under test.

**Comment by jamiesnape** [comment]
FYI @fbudin69500.

**Comment by jamiesnape** [comment]
Do we have a list of data files needed yet? Can we rationalize their locations in Drake to make it more obvious which are part of the API and can be used by external projects, i.e., need installing?

**Comment by jwnimmer-tri** [comment]
This sounds like a Drake issue, not a Shambhala issue?

**Comment by jamiesnape** [comment]
Yes, though I would not object to having cross referenced issues on both in this instance.

**Comment by stonier** [comment]
Detailed issue tracking for this over in https://github.com/RobotLocomotion/drake/issues/6668

**Comment by stonier** [comment]
Examples and manipulation data is now in via: https://github.com/RobotLocomotion/drake/pull/6671
