### ISSUE TITLE
Shambhala on Jenkins failing

### ISSUE THREAD

**Issue by stonier** [RobotLocomotion/drake-shambhala#25]
* [drake-shambhala#5](https://drake-jenkins.csail.mit.edu/job/RobotLocomotion/job/drake-shambhala/job/master/5/console)
* [drake-shambhala#6](https://drake-jenkins.csail.mit.edu/job/RobotLocomotion/job/drake-shambhala/job/master/6/console)

The failures are occuring for `drake_cmake_external`, here:

```
@tinyobjloader//:install: '@tinyobjloader//:install_cmake_config' does not have mandatory provider 'install_actions'
```

In the latter, it is with octomap instead of tinyobjloader. Oddly enough, it is working fine from a build on my pc.

**Comment by jamiesnape** [comment]
It is a Bazel 0.5.3 problem. A fix will be across in Drake shortly.
