### ISSUE TITLE
Shambhala CI Fail

### ISSUE THREAD

**Issue by stonier** [RobotLocomotion/drake-shambhala#43]
Currently failing on the master branch. See [here](https://drake-jenkins.csail.mit.edu/job/RobotLocomotion/job/drake-shambhala/job/master/17/console) - not finding make_unique (c++14 feature).

**Comment by stonier** [comment]
This is happening on the externalAddProject build.

**Comment by stonier** [comment]
Likely some problem around the arguments going into bazel for the compiler.

https://github.com/RobotLocomotion/drake-shambhala/blob/master/drake_cmake_external/CMakeLists.txt#L48

**Comment by jwnimmer-tri** [comment]
I believe the problem is that in addition to passing `--cxxopt=-std=c++1y`, we also need to pass `--host_cxxopt=-std=c++1y`.  Some data-generating tools are compiled for the `host` architecture, instead of `local-opt`, so were not using the option.

**Comment by stonier** [comment]
@jwnimmer-tri Thanks for the hint!
