### ISSUE TITLE
Drake / ROS Octomap Conflict

### ISSUE THREAD

**Issue by stonier** [RobotLocomotion/drake-shambhala#49]
If a ROS environment is sourced, with `ros-kinetic-octomap` installed, then Drake's octomap module will fail to find it's own (v1.7.2) and abort after finding ROS' (v1.8.1). This leaves the `octomap::octomap` target empty.

**Comment by stonier** [comment]
Holding off on resolving this since it may disappear with the folding fcl/ccd/octomap work.

**Comment by jamiesnape** [comment]
We have had this problem for about two years, it predates all the current logic.

**Comment by jamiesnape** [comment]
See https://github.com/RobotLocomotion/drake/pull/7417 and https://github.com/RobotLocomotion/drake/pull/7492.

**Comment by jamiesnape** [comment]
Fixed by RobotLocomotion/drake#7417.
