### ISSUE TITLE
CMake Project Examples

### ISSUE THREAD

**Issue by stonier** [RobotLocomotion/drake-shambhala#6]
To put under CI and be instructive about how to pull Drake into a CMake project. Pulling is via `find_package` or `ExternalProjectAdd`.

@RussTedrake would also like to show (I agree) a lightweight Travis build using a hosted tarball of the installation.

**Comment by stonier** [comment]
How does the above sound?

**Comment by RussTedrake** [comment]
Linking to https://github.com/robotlocomotion/drake/issues/6149 (for those with access).

The above sounds great.  Almost any of the simple executables in the examples directory would be appropriate here.  For instance, implementing examples/simple_continuous_time_system again, but using drake as an external.  Perhaps a similarly simple example using the optimization library, too.  Goal is to document/prototype how we think external projects should use drake.

**Comment by stonier** [comment]
@jamiesnape we need some concrete examples to validate it. As Russ mentioned, examples/simple_continuous_time_system](https://github.com/RobotLocomotion/drake/blob/master/drake/examples/simple_continuous_time_system.cc) is a good example and I think sufficient for a first pass.

**Comment by jamiesnape** [comment]
Sounds good.

**Comment by stonier** [comment]
Let's drop that example in all the drake examples (i.e. bazel and cmake). We should also drop the hello world code then just to keep it simple.

**Comment by jamiesnape** [comment]
Cool, working on it now.

**Comment by jamiesnape** [comment]
Note that the licenses are currently different for this repo and drake and hence `simple_continuous_time_system.cc`.

**Comment by stonier** [comment]
Oversight, let's sync the license here with Drake's.

**Comment by stonier** [comment]
Some update. We cannot do Travis, it has no support for Ubuntu/Xenial. CircleCI is another option, but 2.0 with Xenial support only released yesterday. Likely to be bumpy. There are other options that may be feasible, e.g. docker container builds, but these are likely to be sufficiently complex to defeat the purpose.

For now we will just drop in a simple bash script build on Jenkins. Bash scripts in the project examples.

**Comment by stonier** [comment]
Task List for the 20170713-14 sprint:

Target Platform: Ubuntu/Xenial

* [ ] Jenkins builds and hosts a tarball snapshot of drake (nightly?)(where?)
* [ ] CMake `find_package` project example copies and compiles [examples/simple_continuous_time_system](https://github.com/RobotLocomotion/drake/blob/master/drake/examples/simple_continuous_time_system.cc)
* [ ] CMake `ExternalProject_Add` project example copies and compiles [examples/simple_continuous_time_system](https://github.com/RobotLocomotion/drake/blob/master/drake/examples/simple_continuous_time_system.cc)
* [ ] Jenkins bash scripts inside both cmake project examples
* [ ] Jenkins jobs on our CI server that builds each cmake project examples (nightly?)
* [ ] A nice README.md in each project example

**Comment by RussTedrake** [comment]
@rdeits, @tkoolen -- any ideas for getting around lack of ubuntu support?

**Comment by jwnimmer-tri** [comment]
Travis-CI says to use Docker if you want a Xenial build environment https://github.com/travis-ci/travis-ci/issues/5821#issuecomment-202028783.  I think that's a fine approach for a Xenial flavor of the a prebuilt-Drake-in-other-CI example.

**Comment by jamiesnape** [comment]
I think CircleCI 2.0 would work best for us at this stage.

**Comment by rdeits** [comment]
I set up xenial testing with Docker on Travis for Director: https://github.com/RobotLocomotion/director/blob/master/.travis.yml and it was actually pretty easy.

**Comment by stonier** [comment]
Most jobs covered in PR #8. Will follow up on the remaining in individual issues.
