### ISSUE TITLE
Drake-Shambhala Continuous and Nightly CI is Broken due to Clang-format-4.0 Dependency

### ISSUE THREAD

**Issue by liangfok** [RobotLocomotion/drake-shambhala#67]
See the following two failures:
* https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/RobotLocomotion/job/drake-shambhala/job/master/56/execution/node/18/log/
* https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/RobotLocomotion/job/drake-shambhala/job/master/56/execution/node/18/log/

Relates to #61.

**Comment by liangfok** [comment]
/cc: @stonier (I CC'ed you since I don't have the bits to assign you.)

**Comment by jamiesnape** [comment]
Will be fixed by https://github.com/RobotLocomotion/drake-shambhala/pull/66.
