### ISSUE TITLE
Continuous and Nightly broken "trying to mutate a frozen object"

### ISSUE THREAD

**Issue by m-chaturvedi** [RobotLocomotion/drake-shambhala#68]
[Continuous](https://drake-jenkins.csail.mit.edu/view/Continuous%20Production/job/RobotLocomotion/job/drake-shambhala/job/master/67/consoleText), [Nightly](https://drake-jenkins.csail.mit.edu/view/Nightly%20Production/job/RobotLocomotion/job/drake-shambhala/job/master/67/)

**Comment by jwnimmer-tri** [comment]
Bazel 0.8.0 was released recently, and has changes with respect to list semantics in Skylark code.

**Comment by jwnimmer-tri** [comment]
Proximate cause is #61.

**Comment by jamiesnape** [comment]
> Proximate cause is #61.

Not exactly. Using the latest Bazel on Linux was deliberate since we do not have Mac CI yet.
