### ISSUE TITLE
Drake platform reviewers should be able to approve Shambhala PRs

### ISSUE THREAD

**Issue by jwnimmer-tri** [RobotLocomotion/drake-shambhala#73]
Drake platform reviewers should be able to approve Shambhala PRs.  At a minimum, we want to allow priority fixes to be merged by any of the well-staffed and trusted review crew, instead of blocking on a very busy @stonier.

Relates to #15, but we could fix the permissions in GH earlier without going through all of reviewable.

**Comment by jamiesnape** [comment]
`@RobotLocomotion/drake-platform-review` all have write access and are listed in https://github.com/RobotLocomotion/drake-shambhala/wiki/Reviewable-Setup. Not sure if Reviewable can use the GitHub group to make things a little cleaner...
