### ISSUE TITLE
CircleCI fails: `Could not find a package configuration file provided by "gflags"...`

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake-shambhala#77]
Per this pull request build:
https://circleci.com/gh/RobotLocomotion/drake-shambhala/235

Perhaps the prereqs should be updated to include system `gflags`?

**Comment by stonier** [comment]
You're missing the contents of Jamie's [PR](https://github.com/RobotLocomotion/drake-shambhala/pull/75/files) which went in yesterday. In particular, `drake_cmake_installed/cmake/modules/FindGFlags.cmake`

**Comment by EricCousineau-TRI** [comment]
Whoops! Thought I had rebased. Fixed it - thanks!
