### ISSUE TITLE
Is `drake_cmake_installed/test_find_resource` tested on CI?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake-shambhala#86]
Do we have a guarantee that this test is run on CI?
If not, can we require it?

I ask because I had copied from `find_resource.cc.in` for `test_find_resource.py` for #85, and then seemed to have run into https://github.com/RobotLocomotion/drake/issues/7809

When I tried building / running the test on my machine, it reports `GTEST_NOT_FOUND`, even though I have `libgtest-dev` installed.

\cc @jamiesnape @fbudin69500

**Comment by jamiesnape** [comment]
`libgtest-dev` only installs the source. There was a long thread on a PR or an issue about this and I think @stonier decided to punt in the end.

**Comment by EricCousineau-TRI** [comment]
In that case, can we make `find_resource` not need GTest?

**Comment by jamiesnape** [comment]
We could, but I it depends whether we plan on porting more tests across from drake.
