### ISSUE TITLE
Python Project Example

### ISSUE THREAD

**Issue by stonier** [RobotLocomotion/drake-shambhala#9]
We should probably also exemplify how to pull in an installed drake and use it inside a python project.

@sammy-tri are there pure python only users of drake?

**Comment by sammy-tri** [comment]
There are parts of director which interact with parts of drake only through the python interface...  but I can't think of an example of a project which only uses drake through python off hand.

**Comment by dmsj** [comment]
FWIW, at Draper we would like a pure python workflow for working with drake and pytorch for learning manipulation strategies. 

I would really like a 'setup.py' to install drake for use with a specific python installation. Even better would be a conda package ;-) 

I think there are quite a few applications which would be enabled with a really simple, easy-to-install python interface to Drake.

**Comment by stonier** [comment]
Be interested to learn how you wish to have those two working together. @dmsj are you on slack?

**Comment by dmsj** [comment]
@stonier yup - i'm on Drake Developers. I'll message you there. 

re: use-case - To begin with, we would like to be able to simulate a dynamic system (with contact) and control it with a learned policy implemented in pytorch. We would use the sim for training as well as evaluation.

**Comment by RussTedrake** [comment]
cc @EricCousineau-TRI -- he's about to prioritize cleaning up and expanding the python bindings for drake (including the systems framework).

**Comment by EricCousineau-TRI** [comment]
Closed via #85.
